spring.application.name=groundwater-backend


# Jackson for Java Time
spring.jackson.serialization.write-dates-as-timestamps=false

# Scheduling
spring.main.banner-mode=console
logging.level.root=INFO
logging.level.com.example.backend=INFO

# ===============================
# MongoDB Connection
# ===============================
spring.data.mongodb.uri=mongodb+srv://Yuvi123:hQ5Iyu03OLOiDEBF@cluster0.th4eu8z.mongodb.net/gwlr_db?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=gwlr_db

# ===============================
# Server Config
# ===============================
server.port=8080

# ===============================
# Logging
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
