spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://Yuvi123:hQ5Iyu03OLOiDEBF@cluster0.th4eu8z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=gwlr_db
server.port=8080
