# ===============================
# MongoDB Connection
# ===============================
spring.data.mongodb.uri=mongodb+srv://Yuvi123:<db_password>@cluster0.th4eu8z.mongodb.net/gwlr_db?retryWrites=true&w=majority&appName=Cluster0

# Database name
spring.data.mongodb.database=gwlr_db

# ===============================
# Server Config
# ===============================
server.port=8080

# ===============================
# Logging
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
