import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Supported languages
export type Language = 'en' | 'hi' | 'te' | 'ta' | 'kn' | 'ml' | 'bn' | 'gu' | 'mr' | 'pa';

interface LanguageContextType {
  currentLanguage: Language;
  changeLanguage: (language: Language) => Promise<void>;
  t: (key: string) => string;
  supportedLanguages: typeof languageOptions;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys - comprehensive coverage for all app content
const translations = {
  en: {
    // App Title
    appTitle: 'Groundwater Analytics',
    groundWater: 'Ground Water',
    analytics: 'Analytics',
    
    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    groundwaterMonitoring: 'Groundwater Monitoring',
    liveData: 'Live Data',
    maps: 'Maps',
    reports: 'Reports',
    settings: 'Settings',
    trendAnalysis: 'Trend Analysis',
    
    // Common UI
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    ok: 'OK',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    refresh: 'Refresh',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    select: 'Select',
    clear: 'Clear',
    
    // Settings
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    language: 'Language',
    notifications: 'Notifications',
    preferences: 'Preferences',
    
    // Home Screen
    welcome: 'Welcome to INGRES',
    subtitle: 'Your intelligent groundwater data companion',
    
    // Home Screen Content
    heroTitle: 'Groundwater Monitoring Made Simple',
    heroSubtitle: 'Real-time insights, AI predictions, and risk alerts to help manage water resources responsibly.',
    getStarted: 'Get Started',
    whyThisApp: 'Why This App?',
    whyThisAppDesc: 'Groundwater is the backbone of drinking water, agriculture, and industry. With growing demand and climate challenges, monitoring groundwater levels is critical. Our app provides real-time data and predictive insights to support smarter decisions.',
    keyFeatures: 'Key Features',
    realTimeData: 'Real-time Data',
    realTimeDataDesc: 'Track live groundwater levels from DWLR stations.',
    aiPredictions: 'AI Predictions',
    aiPredictionsDesc: 'Forecast future water levels with accuracy.',
    statusAlerts: 'Status & Alerts',
    statusAlertsDesc: 'Get notified about risks and warnings in your region.',
    interactiveMap: 'Interactive Map',
    interactiveMapDesc: 'Explore groundwater conditions across stations.',
    multilingualSupport: 'Multilingual Support',
    multilingualSupportDesc: 'Access the app in your preferred language.',
    howItWorks: 'How It Works',
    step1: 'Select your language & location.',
    step2: 'View current groundwater trends and AI forecasts.',
    step3: 'Receive alerts and recommendations to plan ahead.',
    whyUseIt: 'Why Use It?',
    forCitizens: 'For citizens',
    forCitizensDesc: 'Stay informed about water availability.',
    forFarmers: 'For farmers',
    forFarmersDesc: 'Plan irrigation wisely.',
    forPolicymakers: 'For policymakers',
    forPolicymakersDesc: 'Support sustainable groundwater management.',
    about: 'About',
    contact: 'Contact',
    credits: 'Credits',
    footerCredit: 'Powered by real-time DWLR data & AI technology',
    
    // Dashboard Content
    overview: 'Overview',
    currentLevel: 'Current Level',
    trend: 'Trend',
    forecast: 'Forecast',
    alerts: 'Alerts',
    monitoring: 'Real-time Monitoring',
    analysis: 'Data Analysis',
    comprehensiveReports: 'Comprehensive Reports',
    features: 'Features',
    waterLevel: 'Water Level',
    lastUpdated: 'Last Updated',
    meters: 'meters',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    
    // Map Content
    location: 'Location',
    station: 'Station',
    stations: 'Stations',
    region: 'Region',
    depth: 'Depth',
    quality: 'Quality',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    
    // Report Content
    generateReport: 'Generate Report',
    downloadReport: 'Download Report',
    shareReport: 'Share Report',
    reportType: 'Report Type',
    dateRange: 'Date Range',
    summary: 'Summary',
    details: 'Details',
    
    // Alerts
    warning: 'Warning',
    critical: 'Critical',
    normal: 'Normal',
    high: 'High',
    low: 'Low',
    moderate: 'Moderate',
    
    // Notification Panel
    markAllRead: 'Mark All Read',
    clearAll: 'Clear All',
    noNotifications: 'No notifications',
    allCaughtUp: 'You\'re all caught up!',
    waterLevels: 'Water Levels',
    predictions: 'Predictions',
    system: 'System',
    tips: 'Tips',
    all: 'All',
    done: 'Done',
    viewDetails: 'View Details',
    takeAction: 'Take Action',
    dismiss: 'Dismiss',
    actionRequired: 'ACTION',
    
    // Notification Messages
    criticalWaterAlert: 'Critical Water Level Alert',
    aiPredictionUpdate: 'AI Prediction Update',
    systemStatusUpdate: 'System Status Update',
    waterConservationTip: 'Water Conservation Tip',
    waterLevelImproving: 'Water Level Improving',
    rechargeOpportunity: 'Recharge Opportunity Detected',
    newStationOnline: 'New Monitoring Station Online',
    dataSync: 'Data Sync Complete',
    maintenanceAlert: 'Maintenance Alert',
    networkExpansion: 'Network Expansion',
    smartIrrigationTip: 'Smart Irrigation Tip',
    rainwaterHarvesting: 'Rainwater Harvesting',
    waterConservation: 'Water Conservation',
    optimalUsage: 'Optimal Usage Time',
    gardenWaterWisdom: 'Garden Water Wisdom',
    monsoonPreparation: 'Monsoon Preparation',
    smartMonitoring: 'Smart Monitoring',
    soilHealth: 'Soil Health',
    realTimeReading: 'Real-time Reading',
    waterQualityUpdate: 'Water Quality Update',
    aiForecastAlert: 'AI Forecast Alert',
    weatherImpactPrediction: 'Weather Impact Prediction',
    seasonalTrendAnalysis: 'Seasonal Trend Analysis',
    demandPrediction: 'Demand Prediction',
    
    // Time formats
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    justNow: 'Just now',
    
    // Sources
    maharashtraWaterBoard: 'Maharashtra Water Board',
    ingresAiModel: 'INGRES AI Model',
    conservationGuide: 'Conservation Guide',
    imdWeatherAi: 'IMD Weather + AI',
    cgwbNetwork: 'CGWB Network',
    mumbaiWaterBoard: 'Mumbai Water Board',
    liveDwlrNetwork: 'Live DWLR Network',
    ingresAiSystem: 'INGRES AI System',
    cgwbMonitoring: 'CGWB Monitoring',
    usageAnalytics: 'Usage Analytics',
    
    // Additional terms for notifications
    dropped: 'dropped',
    increased: 'increased',
    stabilized: 'stabilized',
    trending: 'trending',
    upward: 'upward',
    stable: 'stable',
    waterQuality: 'water quality',
    at: 'at',
    excellent: 'Excellent',
    good: 'Good',
    livedata: 'Live data',
    tip: 'Tip',
  },
  hi: {
    // App Title
    appTitle: 'भूजल विश्लेषण',
    groundWater: 'भूजल',
    analytics: 'विश्लेषण',
    
    // Navigation
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    groundwaterMonitoring: 'भूजल निगरानी',
    liveData: 'लाइव डेटा',
    maps: 'मानचित्र',
    reports: 'रिपोर्ट',
    settings: 'सेटिंग्स',
    trendAnalysis: 'ट्रेंड विश्लेषण',
    
    // Common UI
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    cancel: 'रद्द करें',
    ok: 'ठीक है',
    save: 'सेव करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'अगला',
    previous: 'पिछला',
    refresh: 'ताज़ा करें',
    search: 'खोजें',
    filter: 'फ़िल्टर',
    sort: 'क्रमबद्ध करें',
    select: 'चुनें',
    clear: 'साफ़ करें',
    
    // Settings
    appearance: 'रूप',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    preferences: 'प्राथमिकताएं',
    
    // Home Screen
    welcome: 'INGRES में आपका स्वागत है',
    subtitle: 'आपका बुद्धिमान भूजल डेटा साथी',
    
    // Home Screen Content
    heroTitle: 'भूजल निगरानी सरल बनाई गई',
    heroSubtitle: 'पानी के संसाधनों को जिम्मेदारी से प्रबंधित करने के लिए रियल-टाइम अंतर्दृष्टि, AI भविष्यवाणियां और जोखिम अलर्ट।',
    getStarted: 'शुरू करें',
    whyThisApp: 'यह ऐप क्यों?',
    whyThisAppDesc: 'भूजल पीने के पानी, कृषि और उद्योग की रीढ़ है। बढ़ती मांग और जलवायु चुनौतियों के साथ, भूजल स्तर की निगरानी महत्वपूर्ण है। हमारा ऐप स्मार्ट निर्णयों का समर्थन करने के लिए रियल-टाइम डेटा और भविष्यसूचक अंतर्दृष्टि प्रदान करता है।',
    keyFeatures: 'मुख्य विशेषताएं',
    realTimeData: 'रियल-टाइम डेटा',
    realTimeDataDesc: 'DWLR स्टेशनों से लाइव भूजल स्तर ट्रैक करें।',
    aiPredictions: 'AI भविष्यवाणियां',
    aiPredictionsDesc: 'सटीकता के साथ भविष्य के पानी के स्तर का पूर्वानुमान लगाएं।',
    statusAlerts: 'स्थिति और अलर्ट',
    statusAlertsDesc: 'अपने क्षेत्र में जोखिमों और चेतावनियों के बारे में सूचित रहें।',
    interactiveMap: 'इंटरैक्टिव मानचित्र',
    interactiveMapDesc: 'स्टेशनों में भूजल स्थितियों का अन्वेषण करें।',
    multilingualSupport: 'बहुभाषी समर्थन',
    multilingualSupportDesc: 'अपनी पसंदीदा भाषा में ऐप का उपयोग करें।',
    howItWorks: 'यह कैसे काम करता है',
    step1: 'अपनी भाषा और स्थान का चयन करें।',
    step2: 'वर्तमान भूजल रुझान और AI पूर्वानुमान देखें।',
    step3: 'आगे की योजना बनाने के लिए अलर्ट और सिफारिशें प्राप्त करें।',
    whyUseIt: 'इसका उपयोग क्यों करें?',
    forCitizens: 'नागरिकों के लिए',
    forCitizensDesc: 'पानी की उपलब्धता के बारे में सूचित रहें।',
    forFarmers: 'किसानों के लिए',
    forFarmersDesc: 'सिंचाई की बुद्धिमानी से योजना बनाएं।',
    forPolicymakers: 'नीति निर्माताओं के लिए',
    forPolicymakersDesc: 'टिकाऊ भूजल प्रबंधन का समर्थन करें।',
    about: 'के बारे में',
    contact: 'संपर्क',
    credits: 'क्रेडिट',
    footerCredit: 'रियल-टाइम DWLR डेटा और AI तकनीक द्वारा संचालित',
    
    // Dashboard Content
    overview: 'अवलोकन',
    currentLevel: 'वर्तमान स्तर',
    trend: 'रुझान',
    forecast: 'पूर्वानुमान',
    alerts: 'अलर्ट',
    monitoring: 'रियल-टाइम निगरानी',
    analysis: 'डेटा विश्लेषण',
    comprehensiveReports: 'व्यापक रिपोर्ट',
    features: 'विशेषताएं',
    waterLevel: 'पानी का स्तर',
    lastUpdated: 'अंतिम अपडेट',
    meters: 'मीटर',
    today: 'आज',
    thisWeek: 'इस सप्ताह',
    thisMonth: 'इस महीने',
    thisYear: 'इस साल',
    
    // Map Content
    location: 'स्थान',
    station: 'स्टेशन',
    stations: 'स्टेशन',
    region: 'क्षेत्र',
    depth: 'गहराई',
    quality: 'गुणवत्ता',
    status: 'स्थिति',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    
    // Report Content
    generateReport: 'रिपोर्ट बनाएं',
    downloadReport: 'रिपोर्ट डाउनलोड करें',
    shareReport: 'रिपोर्ट साझा करें',
    reportType: 'रिपोर्ट प्रकार',
    dateRange: 'दिनांक सीमा',
    summary: 'सारांश',
    details: 'विवरण',
    
    // Alerts
    warning: 'चेतावनी',
    critical: 'गंभीर',
    normal: 'सामान्य',
    high: 'उच्च',
    low: 'कम',
    moderate: 'मध्यम',
    
    // Additional Notification System
    tips: 'सुझाव',
    predictions: 'पूर्वानुमान',
    system: 'सिस्टम',
    noNotifications: 'कोई सूचना नहीं',
    markAllAsRead: 'सभी को पढ़े गए के रूप में चिह्नित करें',
    clearAll: 'सभी साफ़ करें',
    waterTips: 'पानी के सुझाव',
    waterPredictions: 'जल पूर्वानुमान',
    waterLevelAlerts: 'जल स्तर चेतावनी',
    systemUpdates: 'सिस्टम अपडेट',
    ago: 'पहले',
    justnow: 'अभी',
    minute: 'मिनट',
    minutes: 'मिनट',
    hour: 'घंटा',
    hours: 'घंटे',
    day: 'दिन',
    days: 'दिन',
    from: 'से',
    indianCouncilAgricultureResearch: 'भारतीय कृषि अनुसंधान परिषद',
    centralGroundWaterBoard: 'केंद्रीय भूजल बोर्ड',
    ministryJalShakti: 'जल शक्ति मंत्रालय',
    govtIndia: 'भारत सरकार',
  },
  te: {
    // App Title
    appTitle: 'భూగర్భజల విశ్లేషణ',
    groundWater: 'భూగర్భజలం',
    analytics: 'విశ్లేషణ',
    
    // Navigation
    home: 'హోమ్',
    dashboard: 'డాష్‌బోర్డ్',
    groundwaterMonitoring: 'భూగర్భజల పర్యవేక్షణ',
    liveData: 'లైవ్ డేటా',
    maps: 'మ్యాప్స్',
    reports: 'రిపోర్ట్స్',
    settings: 'సెట్టింగ్స్',
    trendAnalysis: 'ట్రెండ్ విశ్లేషణ',
    
    // Common UI
    loading: 'లోడవుతోంది...',
    error: 'లోపం',
    success: 'విజయం',
    cancel: 'రద్దు',
    ok: 'సరే',
    save: 'సేవ్',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    close: 'మూసివేయి',
    back: 'వెనుకకు',
    next: 'తరువాత',
    previous: 'మునుపటి',
    refresh: 'రిఫ్రెష్',
    search: 'వెతుకు',
    filter: 'ఫిల్టర్',
    sort: 'క్రమంలో ఉంచు',
    select: 'ఎంచుకోండి',
    clear: 'క్లియర్',
    
    // Settings
    appearance: 'రూపం',
    darkMode: 'డార్క్ మోడ్',
    language: 'భాష',
    notifications: 'నోటిఫికేషన్స్',
    preferences: 'ప్రాధాన్యతలు',
    
    // Home Screen
    welcome: 'INGRES కు స్వాగతం',
    subtitle: 'మీ తెలివైన భూగర్భజల డేటా సహాయకుడు',
    
    // Home Screen Content
    heroTitle: 'భూగర్భజల పర్యవేక్షణ సులభంగా చేయబడింది',
    heroSubtitle: 'నీటి వనరులను బాధ్యతాయుతంగా నిర్వహించడానికి రియల్-టైమ్ అంతర్దృష్టులు, AI అంచనాలు మరియు రిస్క్ అలర్ట్లు.',
    getStarted: 'ప్రారంభించండి',
    whyThisApp: 'ఈ యాప్ ఎందుకు?',
    whyThisAppDesc: 'భూగర్భజలం త్రాగునీరు, వ్యవసాయం మరియు పరిశ్రమలకు వెన్నెముక. పెరుగుతున్న డిమాండ్ మరియు వాతావరణ సవాళ్లతో, భూగర్భజల స్థాయిలను పర్యవేక్షించడం కీలకం. మా యాప్ తెలివైన నిర్ణయాలకు మద్దతు ఇవ్వడానికి రియల్-టైమ్ డేటా మరియు అంచనా అంతర్దృష్టులను అందిస్తుంది.',
    keyFeatures: 'ముఖ్య లక్షణాలు',
    realTimeData: 'రియల్-టైమ్ డేటా',
    realTimeDataDesc: 'DWLR స్టేషన్ల నుండి లైవ్ భూగర్భజల స్థాయిలను ట్రాక్ చేయండి.',
    aiPredictions: 'AI అంచనాలు',
    aiPredictionsDesc: 'ఖచ్చితత్వంతో భవిష్యత్ నీటి స్థాయిలను అంచనా వేయండి.',
    statusAlerts: 'స్థితి & అలర్ట్లు',
    statusAlertsDesc: 'మీ ప్రాంతంలో రిస్క్లు మరియు హెచ్చరికల గురించి తెలుసుకోండి.',
    interactiveMap: 'ఇంటరాక్టివ్ మ్యాప్',
    interactiveMapDesc: 'స్టేషన్లలో భూగర్భజల పరిస్థితులను అన్వేషించండి.',
    multilingualSupport: 'బహుభాషా మద్దతు',
    multilingualSupportDesc: 'మీ ఇష్టపడే భాషలో యాప్‌ను యాక్సెస్ చేయండి.',
    howItWorks: 'ఇది ఎలా పని చేస్తుంది',
    step1: 'మీ భాష & స్థానాన్ని ఎంచుకోండి.',
    step2: 'ప్రస్తుత భూగర్భజల ట్రెండ్లు మరియు AI అంచనాలను చూడండి.',
    step3: 'ముందుగా ప్లాన్ చేయడానికి అలర్ట్లు మరియు సిఫార్సులను అందుకోండి.',
    whyUseIt: 'దీన్ని ఎందుకు ఉపయోగించాలి?',
    forCitizens: 'పౌరుల కోసం',
    forCitizensDesc: 'నీటి లభ్యత గురించి తెలిసి ఉండండి.',
    forFarmers: 'రైతుల కోసం',
    forFarmersDesc: 'నీటిపారుదలను తెలివిగా ప్లాన్ చేయండి.',
    forPolicymakers: 'పాలసీ మేకర్స్ కోసం',
    forPolicymakersDesc: 'స్థిరమైన భూగర్భజల నిర్వహణకు మద్దతు ఇవ్వండి.',
    about: 'గురించి',
    contact: 'సంప్రదించండి',
    credits: 'క్రెడిట్స్',
    footerCredit: 'రియల్-టైమ్ DWLR డేటా & AI టెక్నాలజీతో శక్తివంతం',
    
    // Dashboard Content  
    overview: 'అవలోకనం',
    currentLevel: 'ప్రస్తుత స్థాయి',
    trend: 'ట్రెండ్',
    forecast: 'అంచనా',
    alerts: 'అలర్ట్లు',
    monitoring: 'రియల్-టైమ్ పర్యవేక్షణ',
    analysis: 'డేటా విశ్లేషణ',
    comprehensiveReports: 'సమగ్ర రిపోర్ట్లు',
    features: 'లక్షణాలు',
    waterLevel: 'నీటి స్థాయి',
    lastUpdated: 'చివరిగా అప్‌డేట్ చేయబడింది',
    meters: 'మీటర్లు',
    today: 'ఈరోజు',
    thisWeek: 'ఈ వారం',
    thisMonth: 'ఈ నెల',
    thisYear: 'ఈ సంవత్సరం',
    
    // Map Content
    location: 'స్థానం',
    station: 'స్టేషన్',
    stations: 'స్టేషన్లు',
    region: 'ప్రాంతం',
    depth: 'లోతు',
    quality: 'నాణ్యత',
    status: 'స్థితి',
    active: 'క్రియాశీల',
    inactive: 'నిష్క్రియ',
    
    // Report Content
    generateReport: 'రిపోర్ట్ రూపొందించండి',
    downloadReport: 'రిపోర్ట్ డౌన్‌లోడ్ చేయండి',
    shareReport: 'రిపోర్ట్ భాగస్వామ్యం చేయండి',
    reportType: 'రిపోర్ట్ రకం',
    dateRange: 'తేదీ పరిధి',
    summary: 'సారాంశం',
    details: 'వివరాలు',
    
    // Alerts
    warning: 'హెచ్చరిక',
    critical: 'క్లిష్టం',
    normal: 'సాధారణ',
    high: 'అధిక',
    low: 'తక్కువ',
    moderate: 'మధ్యస్థ',
    
    // Additional Notification System
    tips: 'చిట్కాలు',
    predictions: 'అంచనాలు',
    system: 'సిస్టం',
    noNotifications: 'నోటిఫికేషన్లు లేవు',
    markAllAsRead: 'అన్నింటినీ చదివినట్లు గుర్తించు',
    clearAll: 'అన్నింటినీ క్లియర్ చేయి',
    waterTips: 'నీటి చిట్కాలు',
    waterPredictions: 'నీటి అంచనాలు',
    waterLevelAlerts: 'నీటి స్థాయి హెచ్చరికలు',
    systemUpdates: 'సిస్టం అప్‌డేట్లు',
    ago: 'క్రితం',
    justnow: 'ఇప్పుడే',
    minute: 'నిమిషం',
    minutes: 'నిమిషాలు',
    hour: 'గంట',
    hours: 'గంటలు',
    day: 'రోజు',
    days: 'రోజులు',
    from: 'నుండి',
    indianCouncilAgricultureResearch: 'భారతీయ వ్యవసాయ పరిశోధన మండలి',
    centralGroundWaterBoard: 'కేంద్ర భూగర్భజల బోర్డు',
    ministryJalShakti: 'జల్ శక్తి మంత్రిత్వ శాఖ',
    govtIndia: 'భారత ప్రభుత్వం',
  },
  ta: {
    // App Title
    appTitle: 'நிலத்தடி நீர் பகுப்பாய்வு',
    groundWater: 'நிலத்தடி நீர்',
    analytics: 'பகுப்பாய்வு',
    
    // Navigation
    home: 'முகப்பு',
    dashboard: 'டாஷ்போர்டு',
    groundwaterMonitoring: 'நிலத்தடி நீர் கண்காணிப்பு',
    liveData: 'நேரடி தரவு',
    maps: 'வரைபடங்கள்',
    reports: 'அறிக்கைகள்',
    settings: 'அமைப்புகள்',
    trendAnalysis: 'போக்கு பகுப்பாய்வு',
    
    // Common UI
    loading: 'ஏற்றுகிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
    cancel: 'ரத்து',
    ok: 'சரி',
    save: 'சேமி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    close: 'மூடு',
    back: 'பின்னால்',
    next: 'அடுத்து',
    previous: 'முந்தைய',
    refresh: 'புதுப்பி',
    search: 'தேடு',
    filter: 'வடிகட்டு',
    sort: 'வரிசைப்படுத்து',
    select: 'தேர்வு செய்',
    clear: 'அழி',
    
    // Settings
    appearance: 'தோற்றம்',
    darkMode: 'இருள் பயன்முறை',
    language: 'மொழி',
    notifications: 'அறிவிப்புகள்',
    preferences: 'விருப்பங்கள்',
    
    // Home Screen
    welcome: 'INGRES க்கு வரவேற்கிறோம்',
    subtitle: 'உங்கள் அறிவார்ந்த நிலத்தடி நீர் தரவு துணை',
    
    // Home Screen Content
    heroTitle: 'நிலத்தடி நீர் கண்காணிப்பு எளிதாக்கப்பட்டது',
    heroSubtitle: 'நீர் வளங்களை பொறுப்புடன் நிர்வகிக்க நேரடி நுண்ணறிவுகள், AI கணிப்புகள் மற்றும் அபாய எச்சரிக்கைகள்.',
    getStarted: 'தொடங்குங்கள்',
    whyThisApp: 'ஏன் இந்த ஆப்?',
    whyThisAppDesc: 'நிலத்தடி நீர் குடிநீர், விவசாயம் மற்றும் தொழில்துறையின் முதுகெலும்பு. அதிகரித்து வரும் தேவை மற்றும் காலநிலை சவால்களுடன், நிலத்தடி நீர் மட்டங்களை கண்காணிப்பது முக்கியமானது. எங்கள் ஆப் புத்திசாலித்தனமான முடிவுகளை ஆதரிக்க நேரடி தரவு மற்றும் கணிப்பு நுண்ணறிவுகளை வழங்குகிறது.',
    keyFeatures: 'முக்கிய அம்சங்கள்',
    realTimeData: 'நேரடி தரவு',
    realTimeDataDesc: 'DWLR நிலையங்களிலிருந்து நேரடி நிலத்தடி நீர் மட்டங்களை கண்காணிக்கவும்.',
    aiPredictions: 'AI கணிப்புகள்',
    aiPredictionsDesc: 'துல்லியத்துடன் எதிர்கால நீர் மட்டங்களை முன்னறிவிக்கவும்.',
    statusAlerts: 'நிலை & எச்சரிக்கைகள்',
    statusAlertsDesc: 'உங்கள் பகுதியில் அபாயங்கள் மற்றும் எச்சரிக்கைகளைப் பற்றி அறிந்து கொள்ளுங்கள்.',
    interactiveMap: 'ஊடாடும் வரைபடம்',
    interactiveMapDesc: 'நிலையங்களில் நிலத்தடி நீர் நிலைமைகளை ஆராயுங்கள்.',
    multilingualSupport: 'பல மொழி ஆதரவு',
    multilingualSupportDesc: 'உங்கள் விருப்பமான மொழியில் ஆப்ஸை அணுகவும்.',
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    step1: 'உங்கள் மொழி & இடத்தைத் தேர்ந்தெடுக்கவும்.',
    step2: 'தற்போதைய நிலத்தடி நீர் போக்குகள் மற்றும் AI கணிப்புகளைப் பார்க்கவும்.',
    step3: 'முன்னதாகவே திட்டமிட எச்சரிக்கைகள் மற்றும் பரிந்துரைகளைப் பெறுங்கள்.',
    whyUseIt: 'ஏன் பயன்படுத்த வேண்டும்?',
    forCitizens: 'குடிமக்களுக்கு',
    forCitizensDesc: 'நீர் கிடைக்கும் தன்மையைப் பற்றி தெரிந்து கொள்ளுங்கள்.',
    forFarmers: 'விவசாயிகளுக்கு',
    forFarmersDesc: 'நீர்ப்பாசனத்தை புத்திசாலித்தனமாக திட்டமிடுங்கள்.',
    forPolicymakers: 'கொள்கை வகுப்பாளர்களுக்கு',
    forPolicymakersDesc: 'நிலையான நிலத்தடி நீர் நிர்வாகத்தை ஆதரிக்கவும்.',
    about: 'பற்றி',
    contact: 'தொடர்பு',
    credits: 'வரவுகள்',
    footerCredit: 'நேரடி DWLR தரவு & AI தொழில்நுட்பத்தால் இயக்கப்படுகிறது',
    
    // Dashboard Content
    overview: 'கண்ணோட்டம்',
    currentLevel: 'தற்போதைய நிலை',
    trend: 'போக்கு',
    forecast: 'கணிப்பு',
    alerts: 'எச்சரிக்கைகள்',
    monitoring: 'நேரடி கண்காணிப்பு',
    analysis: 'தரவு பகுப்பாய்வு',
    comprehensiveReports: 'விரிவான அறிக்கைகள்',
    features: 'அம்சங்கள்',
    waterLevel: 'நீர் மட்டம்',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    meters: 'மீட்டர்கள்',
    today: 'இன்று',
    thisWeek: 'இந்த வாரம்',
    thisMonth: 'இந்த மாதம்',
    thisYear: 'இந்த ஆண்டு',
    
    // Map Content
    location: 'இடம்',
    station: 'நிலையம்',
    stations: 'நிலையங்கள்',
    region: 'பகுதி',
    depth: 'ஆழம்',
    quality: 'தரம்',
    status: 'நிலை',
    active: 'செயல்பாட்டில்',
    inactive: 'செயலற்ற',
    
    // Report Content
    generateReport: 'அறிக்கை உருவாக்கு',
    downloadReport: 'அறிக்கை பதிவிறக்கு',
    shareReport: 'அறிக்கை பகிர்',
    reportType: 'அறிக்கை வகை',
    dateRange: 'தேதி வரம்பு',
    summary: 'சுருக்கம்',
    details: 'விவரங்கள்',
    
    // Alerts
    warning: 'எச்சரிக்கை',
    critical: 'முக்கியமான',
    normal: 'சாதாரண',
    high: 'அதிக',
    low: 'குறைவு',
    moderate: 'மிதமான',
    
    // Additional Notification System
    tips: 'குறிப்புகள்',
    predictions: 'முன்னறிவிப்புகள்',
    system: 'அமைப்பு',
    noNotifications: 'அறிவிப்புகள் இல்லை',
    markAllAsRead: 'அனைத்தையும் படித்ததாக குறிக்கவும்',
    clearAll: 'அனைத்தையும் அழிக்கவும்',
    waterTips: 'நீர் குறிப்புகள்',
    waterPredictions: 'நீர் முன்னறிவிப்புகள்',
    waterLevelAlerts: 'நீர் மட்ட எச்சரிக்கைகள்',
    systemUpdates: 'அமைப்பு மேம்படுத்தல்கள்',
    ago: 'முன்',
    justnow: 'இப்போது',
    minute: 'நிமிடம்',
    minutes: 'நிமிடங்கள்',
    hour: 'மணி',
    hours: 'மணி நேரம்',
    day: 'நாள்',
    days: 'நாட்கள்',
    from: 'இருந்து',
    indianCouncilAgricultureResearch: 'இந்திய வேளாண் ஆராய்ச்சி கவுன்சில்',
    centralGroundWaterBoard: 'மத்திய நிலத்தடி நீர் வாரியம்',
    ministryJalShakti: 'ஜல் சக்தி அமைச்சகம்',
    govtIndia: 'இந்திய அரசு',
  },
  kn: {
    // App Title
    appTitle: 'ಅಂತರ್ಜಲ ವಿಶ್ಲೇಷಣೆ',
    groundWater: 'ಅಂತರ್ಜಲ',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    
    // Navigation
    home: 'ಮುಖ್ಯಪುಟ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    groundwaterMonitoring: 'ಅಂತರ್ಜಲ ಮೇಲ್ವಿಚಾರಣೆ',
    liveData: 'ಲೈವ್ ಡೇಟಾ',
    maps: 'ನಕ್ಷೆಗಳು',
    reports: 'ವರದಿಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    trendAnalysis: 'ಪ್ರವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ',
    
    // Common UI
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    error: 'ದೋಷ',
    success: 'ಯಶಸ್ಸು',
    cancel: 'ರದ್ದುಮಾಡಿ',
    ok: 'ಸರಿ',
    save: 'ಉಳಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    back: 'ಹಿಂದೆ',
    next: 'ಮುಂದೆ',
    previous: 'ಹಿಂದಿನ',
    refresh: 'ನವೀಕರಿಸಿ',
    search: 'ಹುಡುಕಿ',
    filter: 'ಫಿಲ್ಟರ್',
    sort: 'ವಿಂಗಡಿಸಿ',
    select: 'ಆಯ್ಕೆಮಾಡಿ',
    clear: 'ತೆರವುಗೊಳಿಸಿ',
    
    // Settings
    appearance: 'ಗೋರಿಕೆ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    language: 'ಭಾಷೆ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    preferences: 'ಆದ್ಯತೆಗಳು',
    
    // Home Screen
    welcome: 'INGRES ಗೆ ಸ್ವಾಗತ',
    subtitle: 'ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಅಂತರ್ಜಲ ಡೇಟಾ ಸಹಚರ',
    
    // Home Screen Content
    heroTitle: 'ಅಂತರ್ಜಲ ಮೇಲ್ವಿಚಾರಣೆ ಸರಳಗೊಳಿಸಲಾಗಿದೆ',
    heroSubtitle: 'ನೀರಿನ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಜವಾಬ್ದಾರಿಯುತವಾಗಿ ನಿರ್ವಹಿಸಲು ನೈಜ-ಸಮಯದ ಒಳನೋಟಗಳು, AI ಮುನ್ಸೂಚನೆಗಳು ಮತ್ತು ಅಪಾಯ ಎಚ್ಚರಿಕೆಗಳು.',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    whyThisApp: 'ಈ ಅಪ್ಲಿಕೇಶನ್ ಏಕೆ?',
    whyThisAppDesc: 'ಅಂತರ್ಜಲವು ಕುಡಿಯುವ ನೀರು, ಕೃಷಿ ಮತ್ತು ಉದ್ಯಮಗಳ ಬೆನ್ನೆಲುಬಾಗಿದೆ. ಹೆಚ್ಚುತ್ತಿರುವ ಬೇಡಿಕೆ ಮತ್ತು ಹವಾಮಾನ ಸವಾಲುಗಳೊಂದಿಗೆ, ಅಂತರ್ಜಲ ಮಟ್ಟವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡುವುದು ನಿರ್ಣಾಯಕವಾಗಿದೆ.',
    keyFeatures: 'ಮುಖ್ಯ ವೈಶಿಷ್ಟ್ಯಗಳು',
    realTimeData: 'ನೈಜ-ಸಮಯದ ಡೇಟಾ',
    realTimeDataDesc: 'DWLR ಕೇಂದ್ರಗಳಿಂದ ಲೈವ್ ಅಂತರ್ಜಲ ಮಟ್ಟಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    aiPredictions: 'AI ಮುನ್ಸೂಚನೆಗಳು',
    aiPredictionsDesc: 'ನಿಖರತೆಯೊಂದಿಗೆ ಭವಿಷ್ಯದ ನೀರಿನ ಮಟ್ಟವನ್ನು ಮುನ್ಸೂಚಿಸಿ.',
    statusAlerts: 'ಸ್ಥಿತಿ ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    statusAlertsDesc: 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿನ ಅಪಾಯಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳ ಬಗ್ಗೆ ತಿಳಿಸಿಕೊಳ್ಳಿ.',
    interactiveMap: 'ಸಂವಾದಾತ್ಮಕ ನಕ್ಷೆ',
    interactiveMapDesc: 'ಕೇಂದ್ರಗಳಲ್ಲಿ ಅಂತರ್ಜಲ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.',
    multilingualSupport: 'ಬಹುಭಾಷಾ ಬೆಂಬಲ',
    multilingualSupportDesc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಅಪ್ಲಿಕೇಶನ್ ಪ್ರವೇಶಿಸಿ.',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    step1: 'ನಿಮ್ಮ ಭಾಷೆ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    step2: 'ಪ್ರಸ್ತುತ ಅಂತರ್ಜಲ ಪ್ರವೃತ್ತಿಗಳು ಮತ್ತು AI ಮುನ್ಸೂಚನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ.',
    step3: 'ಮುಂಚಿತವಾಗಿ ಯೋಜಿಸಲು ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಶಿಫಾರಸುಗಳನ್ನು ಸ್ವೀಕರಿಸಿ.',
    whyUseIt: 'ಇದನ್ನು ಏಕೆ ಬಳಸಬೇಕು?',
    forCitizens: 'ನಾಗರಿಕರಿಗೆ',
    forCitizensDesc: 'ನೀರಿನ ಲಭ್ಯತೆಯ ಬಗ್ಗೆ ತಿಳಿದುಕೊಳ್ಳಿ.',
    forFarmers: 'ರೈತರಿಗೆ',
    forFarmersDesc: 'ನೀರಾವರಿಯನ್ನು ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಯೋಜಿಸಿ.',
    forPolicymakers: 'ನೀತಿ ನಿರ್ಮಾಪಕರಿಗೆ',
    forPolicymakersDesc: 'ಸುಸ್ಥಿರ ಅಂತರ್ಜಲ ನಿರ್ವಹಣೆಯನ್ನು ಬೆಂಬಲಿಸಿ.',
    about: 'ಬಗ್ಗೆ',
    contact: 'ಸಂಪರ್ಕ',
    credits: 'ಕ್ರೆಡಿಟ್‌ಗಳು',
    footerCredit: 'ನೈಜ-ಸಮಯದ DWLR ಡೇಟಾ ಮತ್ತು AI ತಂತ್ರಜ್ಞಾನದಿಂದ ಚಾಲಿತ',
    
    // Dashboard Content
    overview: 'ಅವಲೋಕನ',
    currentLevel: 'ಪ್ರಸ್ತುತ ಮಟ್ಟ',
    trend: 'ಪ್ರವೃತ್ತಿ',
    forecast: 'ಮುನ್ಸೂಚನೆ',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    monitoring: 'ನೈಜ-ಸಮಯದ ಮೇಲ್ವಿಚಾರಣೆ',
    analysis: 'ಡೇಟಾ ವಿಶ್ಲೇಷಣೆ',
    comprehensiveReports: 'ಸಮಗ್ರ ವರದಿಗಳು',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    waterLevel: 'ನೀರಿನ ಮಟ್ಟ',
    lastUpdated: 'ಕೊನೆಯ ಬಾರಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    meters: 'ಮೀಟರ್‌ಗಳು',
    today: 'ಇಂದು',
    thisWeek: 'ಈ ವಾರ',
    thisMonth: 'ಈ ತಿಂಗಳು',
    thisYear: 'ಈ ವರ್ಷ',
    
    // Map Content
    location: 'ಸ್ಥಳ',
    station: 'ಕೇಂದ್ರ',
    stations: 'ಕೇಂದ್ರಗಳು',
    region: 'ಪ್ರದೇಶ',
    depth: 'ಆಳ',
    quality: 'ಗುಣಮಟ್ಟ',
    status: 'ಸ್ಥಿತಿ',
    active: 'ಸಕ್ರಿಯ',
    inactive: 'ನಿಷ್ಕ್ರಿಯ',
    
    // Report Content
    generateReport: 'ವರದಿ ರಚಿಸಿ',
    downloadReport: 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    shareReport: 'ವರದಿ ಹಂಚಿಕೊಳ್ಳಿ',
    reportType: 'ವರದಿ ಪ್ರಕಾರ',
    dateRange: 'ದಿನಾಂಕ ಶ್ರೇಣಿ',
    summary: 'ಸಾರಾಂಶ',
    details: 'ವಿವರಗಳು',
    
    // Alerts
    warning: 'ಎಚ್ಚರಿಕೆ',
    critical: 'ನಿರ್ಣಾಯಕ',
    normal: 'ಸಾಮಾನ್ಯ',
    high: 'ಹೆಚ್ಚಿನ',
    low: 'ಕಡಿಮೆ',
    moderate: 'ಮಧ್ಯಮ',
    
    // Additional Notification System
    tips: 'ಸಲಹೆಗಳು',
    predictions: 'ಮುನ್ನೋಟಗಳು',
    system: 'ವ್ಯವಸ್ಥೆ',
    noNotifications: 'ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    markAllAsRead: 'ಎಲ್ಲವನ್ನೂ ಓದಿದ ಎಂದು ಗುರುತಿಸಿ',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    waterTips: 'ನೀರಿನ ಸಲಹೆಗಳು',
    waterPredictions: 'ನೀರಿನ ಮುನ್ನೋಟಗಳು',
    waterLevelAlerts: 'ನೀರಿನ ಮಟ್ಟದ ಎಚ್ಚರಿಕೆಗಳು',
    systemUpdates: 'ವ್ಯವಸ್ಥೆಯ ನವೀಕರಣಗಳು',
    ago: 'ಹಿಂದೆ',
    justnow: 'ಈಗ',
    minute: 'ನಿಮಿಷ',
    minutes: 'ನಿಮಿಷಗಳು',
    hour: 'ಗಂಟೆ',
    hours: 'ಗಂಟೆಗಳು',
    day: 'ದಿನ',
    days: 'ದಿನಗಳು',
    from: 'ನಿಂದ',
    indianCouncilAgricultureResearch: 'ಭಾರತೀಯ ಕೃಷಿ ಸಂಶೋಧನಾ ಮಂಡಳಿ',
    centralGroundWaterBoard: 'ಕೇಂದ್ರ ಭೂಗರ್ಭ ಜಲ ಮಂಡಳಿ',
    ministryJalShakti: 'ಜಲ್ ಶಕ್ತಿ ಸಚಿವಾಲಯ',
    govtIndia: 'ಭಾರತ ಸರ್ಕಾರ',
  },
  ml: {
    // App Title
    appTitle: 'ഭൂഗർഭജല വിശകലനം',
    groundWater: 'ഭൂഗർഭജലം',
    analytics: 'വിശകലനം',
    
    // Navigation
    home: 'ഹോം',
    dashboard: 'ഡാഷ്ബോർഡ്',
    groundwaterMonitoring: 'ഭൂഗർഭജല നിരീക്ഷണം',
    liveData: 'ലൈവ് ഡാറ്റ',
    maps: 'മാപ്പുകൾ',
    reports: 'റിപ്പോർട്ടുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    trendAnalysis: 'ട്രെൻഡ് വിശകലനം',
    
    // Common UI
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    error: 'പിശക്',
    success: 'വിജയം',
    cancel: 'റദ്ദാക്കുക',
    ok: 'ശരി',
    save: 'സേവ് ചെയ്യുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    close: 'അടയ്ക്കുക',
    back: 'പിന്നിലേക്ക്',
    next: 'അടുത്തത്',
    previous: 'മുമ്പത്തെ',
    refresh: 'റിഫ്രഷ് ചെയ്യുക',
    search: 'തിരയുക',
    filter: 'ഫിൽട്ടർ',
    sort: 'സോർട്ട് ചെയ്യുക',
    select: 'തിരഞ്ഞെടുക്കുക',
    clear: 'ക്ലിയർ ചെയ്യുക',
    
    // Settings
    appearance: 'കാഴ്ച',
    darkMode: 'ഡാർക്ക് മോഡ്',
    language: 'ഭാഷ',
    notifications: 'അറിയിപ്പുകൾ',
    preferences: 'മുൻഗണനകൾ',
    
    // Home Screen
    welcome: 'INGRES-ലേക്ക് സ്വാഗതം',
    subtitle: 'നിങ്ങളുടെ ബുദ്ധിമാനായ ഭൂഗർഭജല ഡാറ്റ കൂട്ടാളി',
    
    // Home Screen Content
    heroTitle: 'ഭൂഗർഭജല നിരീക്ഷണം ലളിതമാക്കി',
    heroSubtitle: 'ജല വിഭവങ്ങൾ ഉത്തരവാദിത്തത്തോടെ കൈകാര്യം ചെയ്യാൻ തത്സമയ ഉൾക്കാഴ്ചകൾ, AI പ്രവചനങ്ങൾ, അപകടസൂചനകൾ.',
    getStarted: 'ആരംഭിക്കുക',
    whyThisApp: 'എന്തുകൊണ്ട് ഈ ആപ്പ്?',
    whyThisAppDesc: 'ഭൂഗർഭജലം കുടിവെള്ളം, കൃഷി, വ്യവസായത്തിന്റെ നട്ടെല്ലാണ്. വർധിച്ചുവരുന്ന ആവശ്യകതയും കാലാവസ്ഥാ വെല്ലുവിളികളും കൊണ്ട്, ഭൂഗർഭജല നിലവാരം നിരീക്ഷിക്കുന്നത് നിർണായകമാണ്.',
    keyFeatures: 'പ്രധാന സവിശേഷതകൾ',
    realTimeData: 'തത്സമയ ഡാറ്റ',
    realTimeDataDesc: 'DWLR സ്റ്റേഷനുകളിൽ നിന്ന് തത്സമയ ഭൂഗർഭജല നിലവാരം ട്രാക്ക് ചെയ്യുക.',
    aiPredictions: 'AI പ്രവചനങ്ങൾ',
    aiPredictionsDesc: 'കൃത്യതയോടെ ഭാവിയിലെ ജലനിലവാരം പ്രവചിക്കുക.',
    statusAlerts: 'സ്ഥിതി & അലേർട്ടുകൾ',
    statusAlertsDesc: 'നിങ്ങളുടെ പ്രദേശത്തെ അപകടങ്ങളെയും മുന്നറിയിപ്പുകളെയും കുറിച്ച് അറിയുക.',
    interactiveMap: 'ഇന്ററാക്ടീവ് മാപ്പ്',
    interactiveMapDesc: 'സ്റ്റേഷനുകളിലെ ഭൂഗർഭജല അവസ്ഥകൾ പരിശോധിക്കുക.',
    multilingualSupport: 'ബഹുഭാഷാ പിന്തുണ',
    multilingualSupportDesc: 'നിങ്ങളുടെ ഇഷ്ടഭാഷയിൽ ആപ്പ് ആക്സസ് ചെയ്യുക.',
    howItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    step1: 'നിങ്ങളുടെ ഭാഷയും സ്ഥലവും തിരഞ്ഞെടുക്കുക.',
    step2: 'നിലവിലെ ഭൂഗർഭജല പ്രവണതകളും AI പ്രവചനങ്ങളും കാണുക.',
    step3: 'മുൻകൂട്ടി ആസൂത്രണം ചെയ്യാൻ അലേർട്ടുകളും ശുപാർശകളും സ്വീകരിക്കുക.',
    whyUseIt: 'എന്തുകൊണ്ട് ഇത് ഉപയോഗിക്കണം?',
    forCitizens: 'പൗരന്മാർക്ക്',
    forCitizensDesc: 'ജല ലഭ്യതയെക്കുറിച്ച് അറിഞ്ഞിരിക്കുക.',
    forFarmers: 'കൃഷിക്കാർക്ക്',
    forFarmersDesc: 'ജലസേചനം ബുദ്ധിപരമായി ആസൂത്രണം ചെയ്യുക.',
    forPolicymakers: 'നയരൂപകർത്താക്കൾക്ക്',
    forPolicymakersDesc: 'സുസ്ഥിര ഭൂഗർഭജല മാനേജ്മെന്റിനെ പിന്തുണയ്ക്കുക.',
    about: 'കുറിച്ച്',
    contact: 'ബന്ധപ്പെടുക',
    credits: 'ക്രെഡിറ്റുകൾ',
    footerCredit: 'തത്സമയ DWLR ഡാറ്റയും AI സാങ്കേതികവിദ്യയും നൽകുന്നത്',
    
    // Dashboard Content
    overview: 'അവലോകനം',
    currentLevel: 'നിലവിലെ നിലവാരം',
    trend: 'പ്രവണത',
    forecast: 'പ്രവചനം',
    alerts: 'അലേർട്ടുകൾ',
    monitoring: 'തത്സമയ നിരീക്ഷണം',
    analysis: 'ഡാറ്റ വിശകലനം',
    comprehensiveReports: 'സമഗ്ര റിപ്പോർട്ടുകൾ',
    features: 'സവിശേഷതകൾ',
    waterLevel: 'ജലനിലവാരം',
    lastUpdated: 'അവസാനം അപ്ഡേറ്റ് ചെയ്തത്',
    meters: 'മീറ്ററുകൾ',
    today: 'ഇന്ന്',
    thisWeek: 'ഈ ആഴ്ച',
    thisMonth: 'ഈ മാസം',
    thisYear: 'ഈ വർഷം',
    
    // Map Content
    location: 'സ്ഥലം',
    station: 'സ്റ്റേഷൻ',
    stations: 'സ്റ്റേഷനുകൾ',
    region: 'പ്രദേശം',
    depth: 'ആഴം',
    quality: 'ഗുണമേന്മ',
    status: 'സ്ഥിതി',
    active: 'സജീവം',
    inactive: 'നിഷ്ക്രിയം',
    
    // Report Content
    generateReport: 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    downloadReport: 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    shareReport: 'റിപ്പോർട്ട് പങ്കിടുക',
    reportType: 'റിപ്പോർട്ട് തരം',
    dateRange: 'തീയതി പരിധി',
    summary: 'സംഗ്രഹം',
    details: 'വിശദാംശങ്ങൾ',
    
    // Alerts
    warning: 'മുന്നറിയിപ്പ്',
    critical: 'നിർണായകം',
    normal: 'സാധാരണ',
    high: 'ഉയർന്ന',
    low: 'കുറഞ്ഞ',
    moderate: 'മിതമായ',
    
    // Additional Notification System
    tips: 'നുറുങ്ങുകൾ',
    predictions: 'പ്രവചനങ്ങൾ',
    system: 'സിസ്റ്റം',
    noNotifications: 'അറിയിപ്പുകളൊന്നുമില്ല',
    markAllAsRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    clearAll: 'എല്ലാം മായ്ക്കുക',
    waterTips: 'ജല നുറുങ്ങുകൾ',
    waterPredictions: 'ജല പ്രവചനങ്ങൾ',
    waterLevelAlerts: 'ജലനിലവാര മുന്നറിയിപ്പുകൾ',
    systemUpdates: 'സിസ്റ്റം അപ്ഡേറ്റുകൾ',
    ago: 'മുൻപ്',
    justnow: 'ഇപ്പോൾ',
    minute: 'മിനിറ്റ്',
    minutes: 'മിനിറ്റുകൾ',
    hour: 'മണിക്കൂർ',
    hours: 'മണിക്കൂറുകൾ',
    day: 'ദിവസം',
    days: 'ദിവസങ്ങൾ',
    from: 'നിന്ന്',
    indianCouncilAgricultureResearch: 'ഇന്ത്യൻ കൗൺസിൽ ഓഫ് അഗ്രികൾച്ചറൽ റിസർച്ച്',
    centralGroundWaterBoard: 'സെൻട്രൽ ഗ്രൗണ്ട് വാട്ടർ ബോർഡ്',
    ministryJalShakti: 'ജൽ ശക്തി മന്ത്രാലയം',
    govtIndia: 'ഇന്ത്യാ ഗവൺമെന്റ്',
  },
  bn: {
    // App Title
    appTitle: 'ভূগর্ভস্থ পানি বিশ্লেষণ',
    groundWater: 'ভূগর্ভস্থ পানি',
    analytics: 'বিশ্লেষণ',
    
    // Navigation
    home: 'হোম',
    dashboard: 'ড্যাশবোর্ড',
    groundwaterMonitoring: 'ভূগর্ভস্থ পানি পর্যবেক্ষণ',
    liveData: 'লাইভ ডেটা',
    maps: 'মানচিত্র',
    reports: 'রিপোর্ট',
    settings: 'সেটিংস',
    trendAnalysis: 'ট্রেন্ড বিশ্লেষণ',
    
    // Common UI
    loading: 'লোড হচ্ছে...',
    error: 'ত্রুটি',
    success: 'সফলতা',
    cancel: 'বাতিল',
    ok: 'ঠিক আছে',
    save: 'সেভ করুন',
    delete: 'মুছে দিন',
    edit: 'সম্পাদনা',
    close: 'বন্ধ করুন',
    back: 'পিছনে',
    next: 'পরবর্তী',
    previous: 'পূর্ববর্তী',
    refresh: 'রিফ্রেশ',
    search: 'খুঁজুন',
    filter: 'ফিল্টার',
    sort: 'সাজান',
    select: 'নির্বাচন করুন',
    clear: 'সাফ করুন',
    
    // Settings
    appearance: 'চেহারা',
    darkMode: 'ডার্ক মোড',
    language: 'ভাষা',
    notifications: 'বিজ্ঞপ্তি',
    preferences: 'পছন্দসমূহ',
    
    // Home Screen
    welcome: 'INGRES এ স্বাগতম',
    subtitle: 'আপনার বুদ্ধিমান ভূগর্ভস্থ পানি ডেটা সহচর',
    
    // Home Screen Content
    heroTitle: 'ভূগর্ভস্থ পানি পর্যবেক্ষণ সহজ করা হয়েছে',
    heroSubtitle: 'পানি সম্পদ দায়িত্বশীলভাবে পরিচালনার জন্য রিয়েল-টাইম অন্তর্দৃষ্টি, AI পূর্বাভাস এবং ঝুঁকি সতর্কতা।',
    getStarted: 'শুরু করুন',
    whyThisApp: 'কেন এই অ্যাপ?',
    whyThisAppDesc: 'ভূগর্ভস্থ পানি পানীয় জল, কৃষি এবং শিল্পের মেরুদণ্ড। ক্রমবর্ধমান চাহিদা এবং জলবায়ু চ্যালেঞ্জের সাথে, ভূগর্ভস্থ পানির স্তর পর্যবেক্ষণ অত্যন্ত গুরুত্বপূর্ণ।',
    keyFeatures: 'মূল বৈশিষ্ট্যসমূহ',
    realTimeData: 'রিয়েল-টাইম ডেটা',
    realTimeDataDesc: 'DWLR স্টেশন থেকে লাইভ ভূগর্ভস্থ পানির স্তর ট্র্যাক করুন।',
    aiPredictions: 'AI পূর্বাভাস',
    aiPredictionsDesc: 'নির্ভুলতার সাথে ভবিষ্যতের পানির স্তর পূর্বাভাস দিন।',
    statusAlerts: 'অবস্থা ও সতর্কতা',
    statusAlertsDesc: 'আপনার এলাকার ঝুঁকি এবং সতর্কতা সম্পর্কে অবগত হন।',
    interactiveMap: 'ইন্টারঅ্যাক্টিভ মানচিত্র',
    interactiveMapDesc: 'স্টেশনগুলিতে ভূগর্ভস্থ পানির অবস্থা অন্বেষণ করুন।',
    multilingualSupport: 'বহুভাষিক সহায়তা',
    multilingualSupportDesc: 'আপনার পছন্দের ভাষায় অ্যাপ অ্যাক্সেস করুন।',
    howItWorks: 'এটি কিভাবে কাজ করে',
    step1: 'আপনার ভাষা ও অবস্থান নির্বাচন করুন।',
    step2: 'বর্তমান ভূগর্ভস্থ পানির প্রবণতা এবং AI পূর্বাভাস দেখুন।',
    step3: 'আগাম পরিকল্পনার জন্য সতর্কতা এবং সুপারিশ গ্রহণ করুন।',
    whyUseIt: 'কেন এটি ব্যবহার করবেন?',
    forCitizens: 'নাগরিকদের জন্য',
    forCitizensDesc: 'পানির প্রাপ্যতা সম্পর্কে অবগত থাকুন।',
    forFarmers: 'কৃষকদের জন্য',
    forFarmersDesc: 'বুদ্ধিমত্তার সাথে সেচের পরিকল্পনা করুন।',
    forPolicymakers: 'নীতিনির্ধারকদের জন্য',
    forPolicymakersDesc: 'টেকসই ভূগর্ভস্থ পানি ব্যবস্থাপনা সমর্থন করুন।',
    about: 'সম্পর্কে',
    contact: 'যোগাযোগ',
    credits: 'কৃতিত্ব',
    footerCredit: 'রিয়েল-টাইম DWLR ডেটা ও AI প্রযুক্তি দ্বারা চালিত',
    
    // Dashboard Content
    overview: 'সংক্ষিপ্ত বিবরণ',
    currentLevel: 'বর্তমান স্তর',
    trend: 'প্রবণতা',
    forecast: 'পূর্বাভাস',
    alerts: 'সতর্কতা',
    monitoring: 'রিয়েল-টাইম পর্যবেক্ষণ',
    analysis: 'ডেটা বিশ্লেষণ',
    comprehensiveReports: 'ব্যাপক রিপোর্ট',
    features: 'বৈশিষ্ট্য',
    waterLevel: 'পানির স্তর',
    lastUpdated: 'সর্বশেষ আপডেট',
    meters: 'মিটার',
    today: 'আজ',
    thisWeek: 'এই সপ্তাহ',
    thisMonth: 'এই মাস',
    thisYear: 'এই বছর',
    
    // Map Content
    location: 'অবস্থান',
    station: 'স্টেশন',
    stations: 'স্টেশনসমূহ',
    region: 'অঞ্চল',
    depth: 'গভীরতা',
    quality: 'গুণমান',
    status: 'অবস্থা',
    active: 'সক্রিয়',
    inactive: 'নিষ্ক্রিয়',
    
    // Report Content
    generateReport: 'রিপোর্ট তৈরি করুন',
    downloadReport: 'রিপোর্ট ডাউনলোড করুন',
    shareReport: 'রিপোর্ট শেয়ার করুন',
    reportType: 'রিপোর্টের ধরন',
    dateRange: 'তারিখের পরিসর',
    summary: 'সারসংক্ষেপ',
    details: 'বিস্তারিত',
    
    // Alerts
    warning: 'সতর্কতা',
    critical: 'গুরুতর',
    normal: 'স্বাভাবিক',
    high: 'উচ্চ',
    low: 'নিম্ন',
    moderate: 'মাঝারি',
    
    // Additional Notification System
    tips: 'পরামর্শ',
    predictions: 'পূর্বাভাস',
    system: 'সিস্টেম',
    noNotifications: 'কোনো বিজ্ঞপ্তি নেই',
    markAllAsRead: 'সবগুলো পড়া হয়েছে হিসেবে চিহ্নিত করুন',
    clearAll: 'সব মুছে ফেলুন',
    waterTips: 'পানির পরামর্শ',
    waterPredictions: 'পানির পূর্বাভাস',
    waterLevelAlerts: 'পানির স্তরের সতর্কতা',
    systemUpdates: 'সিস্টেম আপডেট',
    ago: 'আগে',
    justnow: 'এখনই',
    minute: 'মিনিট',
    minutes: 'মিনিট',
    hour: 'ঘন্টা',
    hours: 'ঘন্টা',
    day: 'দিন',
    days: 'দিন',
    from: 'থেকে',
    indianCouncilAgricultureResearch: 'ভারতীয় কৃষি গবেষণা পরিষদ',
    centralGroundWaterBoard: 'কেন্দ্রীয় ভূগর্ভস্থ পানি বোর্ড',
    ministryJalShakti: 'জল শক্তি মন্ত্রক',
    govtIndia: 'ভারত সরকার',
  },
  gu: {
    // App Title
    appTitle: 'ભૂગર્ભજળ વિશ્લેષણ',
    groundWater: 'ભૂગર્ભજળ',
    analytics: 'વિશ્લેષણ',
    
    // Navigation
    home: 'હોમ',
    dashboard: 'ડેશબોર્ડ',
    groundwaterMonitoring: 'ભૂગર્ભજળ દેખરેખ',
    liveData: 'લાઇવ ડેટા',
    maps: 'નકશા',
    reports: 'રિપોર્ટ્સ',
    settings: 'સેટિંગ્સ',
    trendAnalysis: 'ટ્રેન્ડ વિશ્લેષણ',
    
    // Common UI
    loading: 'લોડ થઈ રહ્યું છે...',
    error: 'ભૂલ',
    success: 'સફળતા',
    cancel: 'રદ કરો',
    ok: 'બરાબર',
    save: 'સેવ કરો',
    delete: 'કાઢી નાખો',
    edit: 'સંપાદિત કરો',
    close: 'બંધ કરો',
    back: 'પાછળ',
    next: 'આગળ',
    previous: 'અગાઉનું',
    refresh: 'રિફ્રેશ કરો',
    search: 'શોધો',
    filter: 'ફિલ્ટર',
    sort: 'ક્રમમાં ગોઠવો',
    select: 'પસંદ કરો',
    clear: 'સાફ કરો',
    
    // Settings
    appearance: 'દેખાવ',
    darkMode: 'ડાર્ક મોડ',
    language: 'ભાષા',
    notifications: 'સૂચનાઓ',
    preferences: 'પસંદગીઓ',
    
    // Home Screen
    welcome: 'INGRES માં આપનું સ્વાગત છે',
    subtitle: 'તમારો બુદ્ધિશાળી ભૂગર્ભજળ ડેટા સાથી',
    
    // Home Screen Content
    heroTitle: 'ભૂગર્ભજળ દેખરેખ સરળ બનાવવામાં આવી છે',
    heroSubtitle: 'જળ સંસાધનોને જવાબદારીપૂર્વક સંચાલિત કરવા માટે રીઅલ-ટાઇમ આંતરદૃષ્ટિ, AI આગાહીઓ અને જોખમ ચેતવણીઓ.',
    getStarted: 'શરૂ કરો',
    whyThisApp: 'આ એપ્લિકેશન શા માટે?',
    whyThisAppDesc: 'ભૂગર્ભજળ પીવાના પાણી, કૃષિ અને ઉદ્યોગનો આધારસ્તંભ છે. વધતી માંગ અને આબોહવાના પડકારો સાથે, ભૂગર્ભજળના સ્તરનું નિરીક્ષણ નિર્ણાયક છે.',
    keyFeatures: 'મુખ્ય વિશેષતાઓ',
    realTimeData: 'રીઅલ-ટાઇમ ડેટા',
    realTimeDataDesc: 'DWLR સ્ટેશનોથી લાઇવ ભૂગર્ભજળ સ્તરનો ટ્રેક કરો.',
    aiPredictions: 'AI આગાહીઓ',
    aiPredictionsDesc: 'ચોકસાઈ સાથે ભવિષ્યના પાણીના સ્તરની આગાહી કરો.',
    statusAlerts: 'સ્થિતિ અને ચેતવણીઓ',
    statusAlertsDesc: 'તમારા વિસ્તારમાં જોખમો અને ચેતવણીઓ વિશે જાણો.',
    interactiveMap: 'ઇન્ટરેક્ટિવ નકશો',
    interactiveMapDesc: 'સ્ટેશનોમાં ભૂગર્ભજળની સ્થિતિઓનું અન્વેષણ કરો.',
    multilingualSupport: 'બહુભાષી સપોર્ટ',
    multilingualSupportDesc: 'તમારી પસંદીદા ભાષામાં એપ્લિકેશન ઍક્સેસ કરો.',
    howItWorks: 'આ કેવી રીતે કાર્ય કરે છે',
    step1: 'તમારી ભાષા અને સ્થાન પસંદ કરો.',
    step2: 'વર્તમાન ભૂગર્ભજળના ટ્રેન્ડ્સ અને AI આગાહીઓ જુઓ.',
    step3: 'આગાહથી યોજના બનાવવા માટે ચેતવણીઓ અને ભલામણો પ્રાપ્ત કરો.',
    whyUseIt: 'શા માટે ઉપયોગ કરવો?',
    forCitizens: 'નાગરિકો માટે',
    forCitizensDesc: 'પાણીની ઉપલબ્ધતા વિશે માહિતગાર રહો.',
    forFarmers: 'ખેડૂતો માટે',
    forFarmersDesc: 'સિંચાઈની બુદ્ધિશાળી યોજના બનાવો.',
    forPolicymakers: 'નીતિ ઘડવૈયાઓ માટે',
    forPolicymakersDesc: 'ટકાઉ ભૂગર્ભજળ વ્યવસ્થાપનને સમર્થન આપો.',
    about: 'વિશે',
    contact: 'સંપર્ક',
    credits: 'ક્રેડિટ્સ',
    footerCredit: 'રીઅલ-ટાઇમ DWLR ડેટા અને AI ટેકનોલોજી દ્વારા સંચાલિત',
    
    // Dashboard Content
    overview: 'ઝાંખી',
    currentLevel: 'વર્તમાન સ્તર',
    trend: 'ટ્રેન્ડ',
    forecast: 'આગાહી',
    alerts: 'ચેતવણીઓ',
    monitoring: 'રીઅલ-ટાઇમ દેખરેખ',
    analysis: 'ડેટા વિશ્લેષણ',
    comprehensiveReports: 'વ્યાપક રિપોર્ટ્સ',
    features: 'વિશેષતાઓ',
    waterLevel: 'પાણીનું સ્તર',
    lastUpdated: 'છેલ્લે અપડેટ થયું',
    meters: 'મીટર',
    today: 'આજે',
    thisWeek: 'આ અઠવાડિયે',
    thisMonth: 'આ મહિને',
    thisYear: 'આ વર્ષે',
    
    // Map Content
    location: 'સ્થાન',
    station: 'સ્ટેશન',
    stations: 'સ્ટેશનો',
    region: 'પ્રદેશ',
    depth: 'ઊંડાઈ',
    quality: 'ગુણવત્તા',
    status: 'સ્થિતિ',
    active: 'સક્રિય',
    inactive: 'નિષ્ક્રિય',
    
    // Report Content
    generateReport: 'રિપોર્ટ બનાવો',
    downloadReport: 'રિપોર્ટ ડાઉનલોડ કરો',
    shareReport: 'રિપોર્ટ શેર કરો',
    reportType: 'રિપોર્ટનો પ્રકાર',
    dateRange: 'તારીખની શ્રેણી',
    summary: 'સારાંશ',
    details: 'વિગતો',
    
    // Alerts
    warning: 'ચેતવણી',
    critical: 'નિર્ણાયક',
    normal: 'સામાન્ય',
    high: 'ઊંચું',
    low: 'નીચું',
    moderate: 'મધ્યમ',
    
    // Additional Notification System
    tips: 'ટિપ્સ',
    predictions: 'અનુમાન',
    system: 'સિસ્ટમ',
    noNotifications: 'કોઈ સૂચનાઓ નથી',
    markAllAsRead: 'બધાને વાંચ્યા તરીકે ચિહ્નિત કરો',
    clearAll: 'બધું સાફ કરો',
    waterTips: 'પાણીની ટિપ્સ',
    waterPredictions: 'પાણીના અનુમાન',
    waterLevelAlerts: 'પાણીના સ્તરની ચેતવણીઓ',
    systemUpdates: 'સિસ્ટમ અપડેટ્સ',
    ago: 'પહેલાં',
    justnow: 'હમણાં',
    minute: 'મિનિટ',
    minutes: 'મિનિટો',
    hour: 'કલાક',
    hours: 'કલાકો',
    day: 'દિવસ',
    days: 'દિવસો',
    from: 'થી',
    indianCouncilAgricultureResearch: 'ભારતીય કૃષિ સંશોધન પરિષદ',
    centralGroundWaterBoard: 'કેન્દ્રીય ભૂગર્ભ જળ બોર્ડ',
    ministryJalShakti: 'જલ શક્તિ મંત્રાલય',
    govtIndia: 'ભારત સરકાર',
  },
  mr: {
    // App Title
    appTitle: 'भूजल विश्लेषण',
    groundWater: 'भूजल',
    analytics: 'विश्लेषण',
    
    // Navigation
    home: 'होम',
    dashboard: 'डॅशबोर्ड',
    groundwaterMonitoring: 'भूजल निरीक्षण',
    liveData: 'लाइव्ह डेटा',
    maps: 'नकाशे',
    reports: 'अहवाल',
    settings: 'सेटिंग्ज',
    trendAnalysis: 'ट्रेंड विश्लेषण',
    
    // Common UI
    loading: 'लोड होत आहे...',
    error: 'त्रुटी',
    success: 'यश',
    cancel: 'रद्द करा',
    ok: 'ठीक आहे',
    save: 'सेव्ह करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    close: 'बंद करा',
    back: 'मागे',
    next: 'पुढे',
    previous: 'मागील',
    refresh: 'रिफ्रेश करा',
    search: 'शोधा',
    filter: 'फिल्टर',
    sort: 'क्रमवारी लावा',
    select: 'निवडा',
    clear: 'साफ करा',
    
    // Settings
    appearance: 'दिसणे',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    notifications: 'सूचना',
    preferences: 'प्राधान्ये',
    
    // Home Screen
    welcome: 'INGRES मध्ये आपले स्वागत आहे',
    subtitle: 'तुमचा हुशार भूजल डेटा साथीदार',
    
    // Home Screen Content
    heroTitle: 'भूजल निरीक्षण सुलभ केले आहे',
    heroSubtitle: 'पाणी संसाधनांचे जबाबदारीने व्यवस्थापन करण्यासाठी रिअल-टाइम अंतर्दृष्टी, AI अंदाज आणि जोखीम इशारे.',
    getStarted: 'सुरुवात करा',
    whyThisApp: 'हे अॅप का?',
    whyThisAppDesc: 'भूजल हे पिण्याचे पाणी, शेती आणि उद्योगाचा आधारस्तंभ आहे. वाढत्या मागणी आणि हवामान आव्हानांसह, भूजल पातळीचे निरीक्षण महत्त्वपूर्ण आहे.',
    keyFeatures: 'मुख्य वैशिष्ट्ये',
    realTimeData: 'रिअल-टाइम डेटा',
    realTimeDataDesc: 'DWLR स्टेशनवरून थेट भूजल पातळी ट्रॅक करा.',
    aiPredictions: 'AI अंदाज',
    aiPredictionsDesc: 'अचूकतेसह भविष्यातील पाणी पातळीचा अंदाज घ्या.',
    statusAlerts: 'स्थिती आणि इशारे',
    statusAlertsDesc: 'तुमच्या क्षेत्रातील जोखीम आणि चेतावणींबद्दल जाणून घ्या.',
    interactiveMap: 'इंटरैक्टिव्ह नकाशा',
    interactiveMapDesc: 'स्टेशनवरील भूजल परिस्थितींचा शोध घ्या.',
    multilingualSupport: 'बहुभाषिक समर्थन',
    multilingualSupportDesc: 'तुमच्या आवडत्या भाषेत अॅप अॅक्सेस करा.',
    howItWorks: 'हे कसे कार्य करते',
    step1: 'तुमची भाषा आणि स्थान निवडा.',
    step2: 'सध्याचे भूजल ट्रेंड आणि AI अंदाज पहा.',
    step3: 'आगाऊ नियोजनासाठी इशारे आणि शिफारसी मिळवा.',
    whyUseIt: 'याचा वापर का करावा?',
    forCitizens: 'नागरिकांसाठी',
    forCitizensDesc: 'पाणी उपलब्धतेबद्दल माहिती ठेवा.',
    forFarmers: 'शेतकऱ्यांसाठी',
    forFarmersDesc: 'सिंचनाचे हुशारीने नियोजन करा.',
    forPolicymakers: 'धोरणकर्त्यांसाठी',
    forPolicymakersDesc: 'टिकाऊ भूजल व्यवस्थापनास समर्थन द्या.',
    about: 'बद्दल',
    contact: 'संपर्क',
    credits: 'श्रेय',
    footerCredit: 'रिअल-टाइम DWLR डेटा आणि AI तंत्रज्ञानाद्वारे चालविले',
    
    // Dashboard Content
    overview: 'अवलोकन',
    currentLevel: 'सध्याची पातळी',
    trend: 'ट्रेंड',
    forecast: 'अंदाज',
    alerts: 'इशारे',
    monitoring: 'रिअल-टाइम निरीक्षण',
    analysis: 'डेटा विश्लेषण',
    comprehensiveReports: 'सर्वसमावेशक अहवाल',
    features: 'वैशिष्ट्ये',
    waterLevel: 'पाणी पातळी',
    lastUpdated: 'शेवटचे अपडेट',
    meters: 'मीटर',
    today: 'आज',
    thisWeek: 'या आठवड्यात',
    thisMonth: 'या महिन्यात',
    thisYear: 'या वर्षी',
    
    // Map Content
    location: 'स्थान',
    station: 'स्टेशन',
    stations: 'स्टेशन्स',
    region: 'प्रदेश',
    depth: 'खोली',
    quality: 'गुणवत्ता',
    status: 'स्थिती',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    
    // Report Content
    generateReport: 'अहवाल तयार करा',
    downloadReport: 'अहवाल डाउनलोड करा',
    shareReport: 'अहवाल शेअर करा',
    reportType: 'अहवालाचा प्रकार',
    dateRange: 'तारीख श्रेणी',
    summary: 'सारांश',
    details: 'तपशील',
    
    // Alerts
    warning: 'चेतावणी',
    critical: 'गंभीर',
    normal: 'सामान्य',
    high: 'उच्च',
    low: 'कमी',
    moderate: 'मध्यम',
    
    // Additional Notification System
    tips: 'टिपा',
    predictions: 'अंदाज',
    system: 'प्रणाली',
    noNotifications: 'कोणत्याही सूचना नाहीत',
    markAllAsRead: 'सर्व वाचले म्हणून चिन्हांकित करा',
    clearAll: 'सर्व साफ करा',
    waterTips: 'पाण्याच्या टिपा',
    waterPredictions: 'पाण्याचे अंदाज',
    waterLevelAlerts: 'पाण्याच्या पातळीच्या चेतावणी',
    systemUpdates: 'प्रणाली अपडेट',
    ago: 'आधी',
    justnow: 'आताच',
    minute: 'मिनिट',
    minutes: 'मिनिटे',
    hour: 'तास',
    hours: 'तास',
    day: 'दिवस',
    days: 'दिवस',
    from: 'पासून',
    indianCouncilAgricultureResearch: 'भारतीय कृषी संशोधन परिषद',
    centralGroundWaterBoard: 'केंद्रीय भूजल मंडळ',
    ministryJalShakti: 'जल शक्ती मंत्रालय',
    govtIndia: 'भारत सरकार',
  },
  pa: {
    // App Title
    appTitle: 'ਭੂਮੀਗਤ ਪਾਣੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    groundWater: 'ਭੂਮੀਗਤ ਪਾਣੀ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    
    // Navigation
    home: 'ਘਰ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    groundwaterMonitoring: 'ਭੂਮੀਗਤ ਪਾਣੀ ਨਿਗਰਾਨੀ',
    liveData: 'ਲਾਈਵ ਡੇਟਾ',
    maps: 'ਨਕਸ਼ੇ',
    reports: 'ਰਿਪੋਰਟਾਂ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    trendAnalysis: 'ਰੁਝਾਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    
    // Common UI
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    error: 'ਗਲਤੀ',
    success: 'ਸਫਲਤਾ',
    cancel: 'ਰੱਦ ਕਰੋ',
    ok: 'ਠੀਕ ਹੈ',
    save: 'ਸੇਵ ਕਰੋ',
    delete: 'ਮਿਟਾਓ',
    edit: 'ਸੰਪਾਦਿਤ ਕਰੋ',
    close: 'ਬੰਦ ਕਰੋ',
    back: 'ਪਿੱਛੇ',
    next: 'ਅਗਲਾ',
    previous: 'ਪਿਛਲਾ',
    refresh: 'ਤਾਜ਼ਾ ਕਰੋ',
    search: 'ਖੋਜੋ',
    filter: 'ਫਿਲਟਰ',
    sort: 'ਕ੍ਰਮਬੱਧ ਕਰੋ',
    select: 'ਚੁਣੋ',
    clear: 'ਸਾਫ਼ ਕਰੋ',
    
    // Settings
    appearance: 'ਦਿਖਾਵਾ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    language: 'ਭਾਸ਼ਾ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    preferences: 'ਤਰਜੀਹਾਂ',
    
    // Home Screen
    welcome: 'INGRES ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    subtitle: 'ਤੁਹਾਡਾ ਬੁੱਧੀਮਾਨ ਭੂਮੀਗਤ ਪਾਣੀ ਡੇਟਾ ਸਾਥੀ',
    
    // Home Screen Content
    heroTitle: 'ਭੂਮੀਗਤ ਪਾਣੀ ਨਿਗਰਾਨੀ ਸਰਲ ਬਣਾਈ ਗਈ',
    heroSubtitle: 'ਪਾਣੀ ਸਰੋਤਾਂ ਨੂੰ ਜ਼ਿੰਮੇਵਾਰੀ ਨਾਲ ਪ੍ਰਬੰਧਿਤ ਕਰਨ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਸੂਝ, AI ਪੂਰਵ-ਅਨੁਮਾਨ ਅਤੇ ਜੋਖਮ ਚੇਤਾਵਨੀਆਂ।',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    whyThisApp: 'ਇਹ ਐਪ ਕਿਉਂ?',
    whyThisAppDesc: 'ਭੂਮੀਗਤ ਪਾਣੀ ਪੀਣ ਵਾਲੇ ਪਾਣੀ, ਖੇਤੀਬਾੜੀ ਅਤੇ ਉਦਯੋਗ ਦੀ ਰੀੜ੍ਹ ਦੀ ਹੱਡੀ ਹੈ। ਵਧਦੀ ਮੰਗ ਅਤੇ ਜਲਵਾਯੂ ਚੁਣੌਤੀਆਂ ਦੇ ਨਾਲ, ਭੂਮੀਗਤ ਪਾਣੀ ਦੇ ਪੱਧਰ ਦੀ ਨਿਗਰਾਨੀ ਮਹੱਤਵਪੂਰਨ ਹੈ।',
    keyFeatures: 'ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    realTimeData: 'ਰੀਅਲ-ਟਾਈਮ ਡੇਟਾ',
    realTimeDataDesc: 'DWLR ਸਟੇਸ਼ਨਾਂ ਤੋਂ ਲਾਈਵ ਭੂਮੀਗਤ ਪਾਣੀ ਦੇ ਪੱਧਰ ਨੂੰ ਟਰੈਕ ਕਰੋ।',
    aiPredictions: 'AI ਪੂਰਵ-ਅਨੁਮਾਨ',
    aiPredictionsDesc: 'ਸਟੀਕਤਾ ਨਾਲ ਭਵਿੱਖ ਦੇ ਪਾਣੀ ਦੇ ਪੱਧਰ ਦਾ ਪੂਰਵ-ਅਨੁਮਾਨ ਲਗਾਓ।',
    statusAlerts: 'ਸਥਿਤੀ ਅਤੇ ਚੇਤਾਵਨੀਆਂ',
    statusAlertsDesc: 'ਆਪਣੇ ਖੇਤਰ ਵਿੱਚ ਜੋਖਮਾਂ ਅਤੇ ਚੇਤਾਵਨੀਆਂ ਬਾਰੇ ਸੂਚਿਤ ਰਹੋ।',
    interactiveMap: 'ਇੰਟਰਐਕਟਿਵ ਨਕਸ਼ਾ',
    interactiveMapDesc: 'ਸਟੇਸ਼ਨਾਂ ਵਿੱਚ ਭੂਮੀਗਤ ਪਾਣੀ ਦੀਆਂ ਸਥਿਤੀਆਂ ਦੀ ਖੋਜ ਕਰੋ।',
    multilingualSupport: 'ਬਹੁ-ਭਾਸ਼ਾਈ ਸਹਾਇਤਾ',
    multilingualSupportDesc: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਵਿੱਚ ਐਪ ਤੱਕ ਪਹੁੰਚ ਕਰੋ।',
    howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    step1: 'ਆਪਣੀ ਭਾਸ਼ਾ ਅਤੇ ਸਥਾਨ ਚੁਣੋ।',
    step2: 'ਮੌਜੂਦਾ ਭੂਮੀਗਤ ਪਾਣੀ ਦੇ ਰੁਝਾਨ ਅਤੇ AI ਪੂਰਵ-ਅਨੁਮਾਨ ਦੇਖੋ।',
    step3: 'ਪਹਿਲਾਂ ਤੋਂ ਯੋਜਨਾ ਬਣਾਉਣ ਲਈ ਚੇਤਾਵਨੀਆਂ ਅਤੇ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ।',
    whyUseIt: 'ਇਸਦੀ ਵਰਤੋਂ ਕਿਉਂ ਕਰੋ?',
    forCitizens: 'ਨਾਗਰਿਕਾਂ ਲਈ',
    forCitizensDesc: 'ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ ਬਾਰੇ ਜਾਣਕਾਰ ਰਹੋ।',
    forFarmers: 'ਕਿਸਾਨਾਂ ਲਈ',
    forFarmersDesc: 'ਸਿੰਚਾਈ ਦੀ ਸਮਝਦਾਰੀ ਨਾਲ ਯੋਜਨਾ ਬਣਾਓ।',
    forPolicymakers: 'ਨੀਤੀ ਨਿਰਮਾਤਾਵਾਂ ਲਈ',
    forPolicymakersDesc: 'ਟਿਕਾਊ ਭੂਮੀਗਤ ਪਾਣੀ ਪ੍ਰਬੰਧਨ ਦਾ ਸਮਰਥਨ ਕਰੋ।',
    about: 'ਬਾਰੇ',
    contact: 'ਸੰਪਰਕ',
    credits: 'ਸਿਹਰਾ',
    footerCredit: 'ਰੀਅਲ-ਟਾਈਮ DWLR ਡੇਟਾ ਅਤੇ AI ਤਕਨਾਲੋਜੀ ਦੁਆਰਾ ਸੰਚਾਲਿਤ',
    
    // Dashboard Content
    overview: 'ਸਮੀਖਿਆ',
    currentLevel: 'ਮੌਜੂਦਾ ਪੱਧਰ',
    trend: 'ਰੁਝਾਨ',
    forecast: 'ਪੂਰਵ-ਅਨੁਮਾਨ',
    alerts: 'ਚੇਤਾਵਨੀਆਂ',
    monitoring: 'ਰੀਅਲ-ਟਾਈਮ ਨਿਗਰਾਨੀ',
    analysis: 'ਡੇਟਾ ਵਿਸ਼ਲੇਸ਼ਣ',
    comprehensiveReports: 'ਵਿਆਪਕ ਰਿਪੋਰਟਾਂ',
    features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    waterLevel: 'ਪਾਣੀ ਦਾ ਪੱਧਰ',
    lastUpdated: 'ਅੰਤਿਮ ਅਪਡੇਟ',
    meters: 'ਮੀਟਰ',
    today: 'ਅੱਜ',
    thisWeek: 'ਇਸ ਹਫ਼ਤੇ',
    thisMonth: 'ਇਸ ਮਹੀਨੇ',
    thisYear: 'ਇਸ ਸਾਲ',
    
    // Map Content
    location: 'ਸਥਾਨ',
    station: 'ਸਟੇਸ਼ਨ',
    stations: 'ਸਟੇਸ਼ਨਾਂ',
    region: 'ਖੇਤਰ',
    depth: 'ਡੂੰਘਾਈ',
    quality: 'ਗੁਣਵੱਤਾ',
    status: 'ਸਥਿਤੀ',
    active: 'ਸਰਗਰਮ',
    inactive: 'ਅਕਿਰਿਆਸ਼ੀਲ',
    
    // Report Content
    generateReport: 'ਰਿਪੋਰਟ ਤਿਆਰ ਕਰੋ',
    downloadReport: 'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',
    shareReport: 'ਰਿਪੋਰਟ ਸਾਂਝੀ ਕਰੋ',
    reportType: 'ਰਿਪੋਰਟ ਦੀ ਕਿਸਮ',
    dateRange: 'ਤਾਰੀਖ ਰੇਂਜ',
    summary: 'ਸੰਖੇਪ',
    details: 'ਵੇਰਵੇ',
    
    // Alerts
    warning: 'ਚੇਤਾਵਨੀ',
    critical: 'ਨਾਜ਼ੁਕ',
    normal: 'ਸਾਧਾਰਨ',
    high: 'ਉੱਚ',
    low: 'ਘੱਟ',
    moderate: 'ਦਰਮਿਆਨਾ',
    
    // Additional Notification System
    tips: 'ਟਿੱਪਸ',
    predictions: 'ਪੂਰਵ ਅਨੁਮਾਨ',
    system: 'ਸਿਸਟਮ',
    noNotifications: 'ਕੋਈ ਸੂਚਨਾਵਾਂ ਨਹੀਂ',
    markAllAsRead: 'ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਹੋਇਆ ਮਾਰਕ ਕਰੋ',
    clearAll: 'ਸਭ ਸਾਫ਼ ਕਰੋ',
    waterTips: 'ਪਾਣੀ ਦੀਆਂ ਟਿੱਪਸ',
    waterPredictions: 'ਪਾਣੀ ਦੇ ਪੂਰਵ ਅਨੁਮਾਨ',
    waterLevelAlerts: 'ਪਾਣੀ ਦੇ ਪੱਧਰ ਦੀਆਂ ਚੇਤਾਵਨੀਆਂ',
    systemUpdates: 'ਸਿਸਟਮ ਅੱਪਡੇਟਸ',
    ago: 'ਪਹਿਲਾਂ',
    justnow: 'ਹੁਣੇ',
    minute: 'ਮਿੰਟ',
    minutes: 'ਮਿੰਟ',
    hour: 'ਘੰਟਾ',
    hours: 'ਘੰਟੇ',
    day: 'ਦਿਨ',
    days: 'ਦਿਨ',
    from: 'ਤੋਂ',
    indianCouncilAgricultureResearch: 'ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਖੋਜ ਕੌਂਸਲ',
    centralGroundWaterBoard: 'ਕੇਂਦਰੀ ਭੂਮੀਗਤ ਪਾਣੀ ਬੋਰਡ',
    ministryJalShakti: 'ਜਲ ਸ਼ਕਤੀ ਮੰਤਰਾਲਾ',
    govtIndia: 'ਭਾਰਤ ਸਰਕਾਰ',
  }
};

// Language names with flags for the selector
export const languageOptions = [
  { code: 'en' as Language, name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi' as Language, name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'te' as Language, name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta' as Language, name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'kn' as Language, name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml' as Language, name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'bn' as Language, name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'gu' as Language, name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'mr' as Language, name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'pa' as Language, name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  // Load saved language on startup
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem('app_language');
        if (savedLanguage && (Object.keys(translations) as Language[]).includes(savedLanguage as Language)) {
          setCurrentLanguage(savedLanguage as Language);
        }
      } catch (error) {
        console.log('Error loading language preference:', error);
      }
    };

    loadLanguage();
  }, []);

  // Change language and save to storage
  const changeLanguage = async (language: Language) => {
    try {
      setCurrentLanguage(language);
      await AsyncStorage.setItem('app_language', language);
    } catch (error) {
      console.log('Error saving language preference:', error);
    }
  };

  // Translation function
  const t = (key: string): string => {
    const languageTranslations = translations[currentLanguage];
    const fallbackTranslations = translations.en;
    
    return (languageTranslations as any)[key] || (fallbackTranslations as any)[key] || key;
  };

  const value: LanguageContextType = {
    currentLanguage,
    changeLanguage,
    t,
    supportedLanguages: languageOptions,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
